services:
  zigana.gateway:
    image: ${DOCKER_REGISTRY-}ziganagateway
    depends_on:
      db:
       condition: service_healthy
    build:
      context: .
      dockerfile: src/Zigana.Gateway/Dockerfile

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
